logging:
    level:
        tk.mybatis: DEBUG
        com.zeunpro.po.biz.portal: DEBUG
#       config: classpath:logback.xml
    path: /zppo-biz-portal
spring:
    application:
        name: zppo-biz-portal
    zipkin:
        base-url: http://192.168.15.12:9411
    sleuth:
        sampler:
            percentage: 1.0        
    boot:
        admin:
             url: http://192.168.15.11:9010 #健康监控
    datasource:
        name: test
        url: jdbc:mysql:loadbalance://192.168.15.162:3306,192.168.15.163:3306/zppo_portal?roundRobinLoadBalance=true&useUnicode=true&characterEncoding=UTF8        
        username: root
        password: poi098)(*
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        database: 0
        hostName: 192.168.15.108
        port: 6379
        timeout: 0
        password: zeunpro168
        pool:
          maxTotal: 200
          maxWaitMillis: 10000
          maxIdle: 50
          minIdle: 10
          testOnBorrow: true
    rabbitmq:
        host: 192.168.15.111
        port: 5672
        username: user
        password: passwordrabbit
    cloud:
        stream:
            bindings:
               mq_channel_order:
                      group: group_user
    http:
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 50Mb

mybatis:
    basepackage: com.zeunpro.po.biz.portal.dao
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 6250

eureka:
    instance:
#        #statusPageUrlPath: ${management.context-path}/info
#        #healthCheckUrlPath: ${management.context-path}/health
        lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
        lease-expiration-duration-in-seconds: 10      # 发呆时间，即服务续约到期时间（缺省为90s）
        prefer-ip-address: true
       #hostname: 127.0.0.1
        hostname: 192.168.15.10
        port: 9090
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
        healthcheck:
           enabled: true   # 开启健康检查（依赖spring-boot-starter-actuator）

#feign:
#  hystrix:
#    enabled: true
               
             
               
security:
  oauth2:
    resource:
       filter-order: 3
       jwt:
         keyValue:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----