logging:
    level:
        tk.mybatis: DEBUG
        com.zeunpro.po.biz.portal: DEBUG
#       config: classpath:logback.xml
    path: /zppo-biz-portal
spring:
    datasource:
        name: test
        url: jdbc:mysql:loadbalance://192.168.15.162:3306,192.168.15.163:3306/zppo_portal?roundRobinLoadBalance=true&useUnicode=true&characterEncoding=UTF8        
        username: root
        password: poi098)(*
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    